import React, { memo } from 'react';
import LayoutPage from '../components/layouts/layoutPage';
import LayoutScreen from '../components/layouts/layoutScreen';

const Privacy = () => {
  return (
    <LayoutPage>
      <LayoutScreen title='Privacy' description='Klik'>
        <section className='container'>
          <div className="color-b" style={{ fontSize: 16 }}>
            1)	Introduction. Welcome to Klik, owned and operated by Salt Holdings, Inc. d/b/a Klik (“Metasalt,” “we,” “us”, or “our”). Klik is a fun, new social media app that uses non-fungible tokens (“NFTs”) to build community and engagement amongst its users.
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	You are reading the terms of service (the “Terms”), which govern the relationship and serve as an agreement between you and us and set forth the terms and conditions by which you may access and use the Platform and our related websites, services, applications, products and content (collectively, the “Services”). These Terms of Service (“Terms”) govern your access to and use of the Klik website(s), our APIs, mobile applications (“App”), and any live support, software, tools, features, or functionalities provided on or in connection with our services; including without limitation using our services to view, explore, help display and create NFTs, and using our tools, at your own discretion, to connect directly with others to mint, purchase, sell, or transfer NFTs on public blockchains (collectively, the “Service”). “NFT” in these Terms means a non-fungible token or similar digital item implemented on a blockchain (such as the Ethereum blockchain), which uses smart contracts to link to or otherwise be associated with certain content or data. Access to certain Services or features of the Services (such as, by way of example and not limitation, the ability to submit or share User Content (defined below)) may be subject to age restrictions and not available to all users of the Services.</li>
              <li>	For purposes of these Terms, “you” and “your” means you as the user of the Services. The Terms form a legally binding agreement between you and us. Please take the time to read them carefully. If you are under age 18, you may only use the Services with the consent of your parent or legal guardian. Please be sure your parent or legal guardian has reviewed and discussed these Terms with you. If you use the Service on behalf of a company or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity’s behalf.</li>
              <li>	PLEASE READ THESE TERMS OF SERVICE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION AND AFFECT YOUR LEGAL RIGHTS. THEY INCLUDE A MANDATORY ARBITRATION AGREEMENT AND CLASS ACTION WAIVER WHICH (WITH LIMITED EXCEPTIONS) REQUIRE ANY DISPUTES BETWEEN US TO BE RESOLVED THROUGH INDIVIDUAL ARBITRATION RATHER THAN BY A JUDGE OR JURY IN COURT.</li>
              <li>	BY CLICKING TO ACCEPT, SIGN, AND/OR USING OUR SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE SERVICE.</li>
              <li>	Klik is a social media company that uses NFT technology to help build community and engagement. We are not a wallet provider, exchange, broker, dealer, financial institution, payments processor, money services business, or creditor. Klik provides a peer-to-peer web3 service that helps users discover and directly interact with each other and NFTs available on public blockchains to access social media content such as, but not limited to videos, music, chatrooms, and livestreams, QR codes, and hyperlinks. We do not have custody or control over the NFTs or blockchains you are interacting with and we do not execute or effectuate purchases, transfers, or sales of NFTs. To use our Service, you must use a third-party wallet which allows you to engage in transactions on blockchains.</li>
              <li>	Klik is not party to any agreement between any users. You bear full responsibility for verifying the identity, legitimacy, and authenticity of NFTs that you purchase from third-party sellers using the Service and we make no claims, guarantees, or recommendations about the identity, legitimacy, functionality, or authenticity of users or NFTs (and any content associated with such NFTs) visible on the Service.</li>
              <li>	We may provide an authentication service for a fee, but such authentication is subject to conditions, namely, that the NFT to be authenticated was minted on Klik, and that our authentication service is paid with Klik Tokens (MST).  To be clear, MST are not fractionalized shares. MST are merely an alternative form of payment for certain services rendered on Klik, e.g., authentication of NFTs minted on Klik. Think of MST as an arcade token.</li>
              <li>	Because we have a growing number of services, we sometimes need to provide additional terms for specific services (and such services are deemed part of the “Service” hereunder and shall also be subject to these Terms). Those additional terms and conditions, which are available with the relevant service, then become part of your agreement with us if you use those services. In the event of a conflict between these Terms and any additional applicable terms we may provide for a specific service, such additional terms shall control for that specific service.</li>
              <li>	Klik reserves the right to change or modify these Terms at any time and in our sole discretion. If we make material changes to these Terms, we will use reasonable efforts to provide notice of such changes, such as by providing notice through the Service or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference effective as of the date these Terms are updated. It is your sole responsibility to review the Terms from time to time to view such changes and to ensure that you understand the terms and conditions that apply when you access or use the Service.</li>
            </ol>
            <br />
            2)	Accessing the Service. Your access to and use of the Services is subject to these Terms and all applicable laws and regulations.
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	Your blockchain address functions as your identity on Klik, but you may choose to rely on self-identification such as adding a Twitter handle, Discord username, or identifying information to your Klik profile. You will need a blockchain address and a third-party wallet to access certain NFT services such minting, buying, and selling NFT, but you can enjoy the social media content without engaging any of the NFT activities. Nonetheless, your account on the Service (“Account”) will be associated with your blockchain address if you choose to participate in NFT activities.</li>
              <li>	We rely on 3rd party services such as Web3auth to enable quick and easy wallet creation using your social accounts such as Facebook, Twitter, Google, Discord, Instagram, Apple ID, and any other OAuth providers.  Our list of social authorization logins to create your wallet using 3rd party software such as Web3Auth continues to grow and the list above is not exhaustive. If you choose to sign-up or log-in to Klik using a third-party service such as Facebook, Twitter, Instagram, or Google, or link your Klik account to a third-party service, we may collect information from the service–for example, your public profile information (such as nickname), email, and contact list. Social authorized logins, such as through your Twitter Profile inherently contain identifying information used to create your wallet that may be passed onto us, such as your Twitter handle or email address.  Your blockchain wallet address functions as your identity on Klik but not the only way to identify you.</li>
              <li>	In most cases, your Account on Klik will be associated with your linked blockchain address and display the NFTs for that blockchain address (and, if applicable, any content associated with such NFTs). By using your wallet in connection with the Service, you agree that you are using that wallet under the terms and conditions of the applicable provider of the wallet. Wallets are not operated by, maintained by, or affiliated with Klik, and Klik does not have custody or control over the contents of your wallet and has no ability to retrieve or transfer its contents. Klik accepts no responsibility for, or liability to you, in connection with your use of a wallet and makes no representations or warranties regarding how the Service will operate with any specific wallet. You are solely responsible for keeping your wallet secure and you should never share your wallet credentials or seed phrase with anyone. If you discover an issue related to your wallet, please contact your wallet provider. Likewise, you are solely responsible for your Account and any associated wallet and we are not liable for any acts or omissions by you in connection with your Account or as a result of your Account or wallet being compromised. You agree to immediately notify us if you discover or otherwise suspect any security issues related to the Service or your Account.</li>
              <li>	We rely on 3rd party partners to enable credit card payment or purchase of crypto subject to local and country laws. These are collectively known as NFT gateways, checkout processors or fiat on-ramps.  These gateways accept credit card payments and exchange them for cryptocurrency or a smart contract call. Their service fees range from 3-5% which is charged on top of the price paid for crypto/token. We may elect to receive a portion of those fees. Their service fee is separate from our platform fee of 5%, which is incurred for sale of an NFT on Klik. These gateways require Proof of ID, Selfie and Proof of Address to fulfill their Know Your Customer (KYC) requirements. Currently, over 198 countries (https://support.wert.io/en/articles/5194509-supported-countries) and a select number of US states are supported (https://support.wert.io/en/articles/5194514-supported-us-states). You agree to all applicable rules and policies required by our 3rd party partners.</li>
              <li>	You also represent and warrant that you will comply with all applicable laws (e.g., local, state, federal and other laws) in connection with using the Service. In order to comply with our legal obligations and keep our users and platform safe, we may need to restrict, suspend, or terminate your access to the Service. You acknowledge that Klik is under no obligation to disclose the details of its decision to take such action with you.</li>
              <li>	Without limiting the foregoing, by using the Service, you represent and warrant that: (a) you are not located in, ordinarily resident in, or organized under the laws of any jurisdiction that is subject to a comprehensive U.S. Government embargo ("Embargoed Jurisdiction"); (b) you are not subject to any sanctions administered by an agency of the U.S. Government, any other government, or the United Nations (collectively, “Sanctions”); (c) you are not owned or controlled, directly or indirectly, by any person that is subject to Sanctions, or that is located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction; (d) none of your officers, managers, directors, shareholders or authorized representatives is subject to Sanctions, or is located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction, or is owned or controlled, directly or indirectly, by any person that is subject to Sanctions or that is located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction; (e) you have not transacted and will not transact with any person or entity falling into any of (a)-(d); (f) you have not transacted and will not transact for the benefit of any person or entity falling into any of (a)-(d). You further covenant that the foregoing shall be true during the entire period of this agreement. If you access or use the Service outside the United States, you are solely responsible for ensuring that your access and use of the Service in such country, territory or jurisdiction does not violate any applicable laws.</li>
              <li>	Klik may require you to provide additional information and documents in certain circumstances, such as at the request of any government authority, as any applicable law or regulation dictates, to provide you with a requested service, or to investigate a potential violation of these Terms. In such cases, Klik, in its sole discretion, may disable your Account and block your ability to access the Service until such additional information and documents are processed by Klik. If you do not provide complete and accurate information in response to such a request, Klik may refuse to restore your access to the Service.</li>
              <li>	Your access and use of the Service may be interrupted from time to time for any of several reasons, including, without limitation, the malfunction of equipment, periodic updating, maintenance, or repair of the Service, geographic restrictions, potential violation of these Terms, or other actions that Klik, in its sole discretion, may elect to take. You understand that Klik, in its sole discretion, may disable your Account and/or reassign your username or associated URL.</li>
            </ol>

            <br />
            3)	Third-Party Content, Agreements, and Services. You acknowledge and accept the following:
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	Because we provide peer-to-peer Web3 services, Klik helps you explore NFTs created by third parties and interact with different blockchains. Klik does not make any representations or warranties about this third-party content visible through our Service, including any content associated with NFTs displayed on the Service, and you bear responsibility for verifying the legitimacy, authenticity, and legality of NFTs that you purchase from third-party sellers. We also cannot guarantee that any NFTs visible on Klik will always remain visible and/or available to be bought, sold, or transferred. Users are solely responsible for any content related to their NFTs.</li>
              <li>	These Terms solely govern the use of our Service. NFTs are available on public blockchains, are purchased, sold, or transferred between a buyer, seller and/or creator directly, and may be purchased, sold, or transferred by buyers, sellers, and/or creators without the use of our Service and therefore without agreeing to our Terms. There may be terms and conditions that apply to the NFTs' themselves set directly between buyers, sellers, and/or creators with respect to the NFT including with respect to the use of the NFT content and rights and obligations associated with a given NFT ("NFT Terms"). For example, when you click to get more details about any of the NFTs or NFT collections visible on Klik or view the NFT metadata, you may notice a third-party link to NFT Terms governing the use of the NFT that you will be required to comply with. Klik does not set the NFT Terms and is not party to any such NFT Terms, which are solely between the buyer, seller, and/or creator. The buyer, seller, and/or creator are entirely responsible for communicating, promulgating, agreeing to, and enforcing NFT Terms. You are responsible for reviewing such NFT Terms.</li>
              <li>	Sellers are solely responsible for determining and establishing the price of an NFT, inclusive of any applicable tax. Additionally, to the extent applicable, they are solely responsible for any mint count and minting mechanics for NFTs they sell.</li>
              <li>	For its Service, Klik may receive certain fees. Klik does not set, collect, or determine other applicable costs, fees, and expenses associated with buying and selling an NFT, including but not limited to any creator earnings, gas, or transaction fees. These costs, fees, and expenses are paid directly to the seller, creator, payment processor, blockchain validator, or other third party, as applicable. Because these costs, fees, and expenses are not collected by Klik, it cannot refund them.</li>
              <li>	The Service may also contain links or functionality to access or use third-party websites (“Third-Party Websites”) and applications (“Third-Party Applications”), or otherwise display, include, or make available content, data, information, services, applications, or materials from third parties (“Third-Party Materials”). When you click on a link to, or access and use, a Third-Party Website or Third-Party Application, though we may not warn you that you have left our Service, you are subject to the terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites, Third-Party Applications, and Third-Party Materials are not under the control of Klik, and may be “open” applications for which no recourse is possible. Klik is not responsible or liable for any Third-Party Websites, Third-Party Applications, and Third-Party Materials. Klik provides links to these Third-Party Websites and Third-Party Applications only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites or Third-Party Applications, or their products or services or associated Third-Party Materials. You use all links in Third-Party Websites, Third-Party Applications, and Third-Party Materials at your own risk.</li>
            </ol>
            <br />

            4)	Assumption of Risk of NFTs. NFTs are not Shares in a Common Enterprise. NFTS have no reasonable expectation of Profit. You accept and acknowledge the following:
            <ol style={{ listStyleType: 'lower-alpha' }}>

              <li>	Although we list the current value of the NFTs in your wallet, the actual value of an NFT is subjective. Prices of NFTs are subject to volatility and fluctuations in the price of cryptocurrency can also materially and adversely affect NFT prices. You acknowledge that you fully understand this subjectivity and volatility and that you may lose money. Hence, you should have no reasonable expectation of profit. NFTs even those sold under an ERC1155 contract are and should not be construed as shares in a common enterprise. NFTs including those fractionalized cannot be sold with marketing statements suggesting that such fractionalized interests will increase in value. NFT creators shall not make promises or suggestions of price appreciation of NFTs, fractionalized or otherwise. NFTs created on this platform have utility and are not securities. The NFTs created on this platform are passes or digital tickets to access content.</li>
              <li>	You understand that you are responsible for any fees related to use of the Service, including for actions you take on the blockchain, regardless of whether a successful transaction occurs, and that such fees are final and irreversible.</li>
              <li>	A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications, and could therefore also negatively impact the potential utility of NFTs.</li>
              <li>	The regulatory regime governing blockchain technologies, non-fungible tokens, cryptocurrency, and other crypto-based items is uncertain, and new regulations or policies may materially adversely affect the development of the Service and the utility of NFTs.</li>
              <li>	You are solely responsible for determining what, if any, taxes apply to your transactions and to withhold, collect, report, and remit the correct amounts of taxes to the appropriate tax authorities. Klik is not responsible for determining, withholding, collecting, reporting, or remitting any taxes that apply to your NFTs or the sale/purchase of your NFTs.</li>
              <li>	There are risks associated with purchasing items associated with content created by third parties through peer-to-peer transactions, including but not limited to, the risk of purchasing counterfeit items, mislabeled items, items that are vulnerable to metadata decay, items on smart contracts with bugs, and items that may become untransferable. You represent and warrant that you have done sufficient research before making any decisions to sell, obtain, transfer, or otherwise interact with any NFTs or accounts/collections.</li>
              <li>	We do not have ownership or control of the smart contracts deployed by third parties, and are not responsible and make no guarantees regarding their operation and functionality.</li>
              <li>	We do not control the public blockchains that you are interacting with and we do not control certain smart contracts and protocols that may be integral to your ability to complete transactions on these public blockchains. Additionally, blockchain transactions are irreversible and Klik has no ability to reverse any transactions on the blockchain.</li>
              <li>	There are risks associated with using Internet and blockchain based products, including, but not limited to, the risk associated with hardware, software, and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to your third-party wallet or Account. You accept and acknowledge that Klik will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Service or any Blockchain network, however caused.</li>
              <li>	The Service relies on third-party platforms and/or vendors. If we are unable to maintain a good relationship with such platform providers and/or vendors; if the terms and conditions or pricing of such platform providers and/or vendors change; if we violate or cannot comply with the terms and conditions of such platforms and/or vendors; or if any of such platforms and/or vendors loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Service will suffer.</li>
              <li>	Klik reserves the right to hide collections, contracts, and items affected by any of these issues or by other issues. Items you purchase may become inaccessible on Klik. Under no circumstances shall the inability to view items on Klik or an inability to use the Service in conjunction with the purchase, sale, or transfer of items available on any blockchains serve as grounds for a claim against Klik.</li>
              <li>	If you have a dispute with one or more users, YOU RELEASE US FROM CLAIMS, DEMANDS, AND DAMAGES OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES. IN ENTERING INTO THIS RELEASE, YOU EXPRESSLY WAIVE ANY PROTECTIONS (WHETHER STATUTORY OR OTHERWISE) THAT WOULD OTHERWISE LIMIT THE COVERAGE OF THIS RELEASE TO INCLUDE THOSE CLAIMS WHICH YOU MAY KNOW OR SUSPECT TO EXIST IN YOUR FAVOR AT THE TIME OF AGREEING TO THIS RELEASE.</li>
            </ol>
            <br />

            5)	User conduct. As a social media app that is focused on fun and community, you may not:
            <ol style={{ listStyleType: 'lower-alpha' }}>

              <li>	access or use the Services if you are not fully able and legally competent to agree to these Terms or are authorized to use the Services by your parent or legal guardian;</li>
              <li>	make unauthorized copies, modify, adapt, translate, reverse engineer, disassemble, decompile or create any derivative works of the Services or any content included therein, including any files, tables or documentation (or any portion thereof) or determine or attempt to determine any source code, algorithms, methods or techniques embodied by the Services or any derivative works thereof;</li>
              <li>	distribute, license, transfer, or sell, in whole or in part, any of the Services or any derivative works thereof</li>
              <li>	market, rent or lease the Services for a fee or charge, or use the Services to advertise or perform any commercial solicitation;</li>
              <li>	use the Services, without our express written consent, for any commercial or unauthorized purpose, including communicating or facilitating any commercial advertisement or solicitation or spamming;</li>
              <li>	interfere with or attempt to interfere with the proper working of the Services, disrupt our website or any networks connected to the Services, or bypass any measures we may use to prevent or restrict access to the Services;</li>
              <li>	incorporate the Services or any portion thereof into any other program or product. In such case, we reserve the right to refuse service, terminate accounts or limit access to the Services in our sole discretion;</li>
              <li>	use automated scripts to collect information from or otherwise interact with the Services;</li>
              <li>	impersonate any person or entity, or falsely state or otherwise misrepresent you or your affiliation with any person or entity, including giving the impression that any content you upload, post, transmit, distribute or otherwise make available emanates from the Services;</li>
              <li>	intimidate or harass another, or promote sexually explicit material, violence or discrimination based on race, sex, religion, nationality, disability, sexual orientation or age;</li>
              <li>	use or attempt to use another’s account, service or system without authorization from Klik, or create a false identity on the Services;</li>
              <li>	use the Services in a manner that may create a conflict of interest or undermine the purposes of the Services, such as trading reviews with other users or writing or soliciting fake reviews;</li>
              <li>	use the Services to upload, transmit, distribute, store or otherwise make available in any way: files that contain viruses, trojans, worms, logic bombs or other material that is malicious or technologically harmful;</li>
              <li>	any unsolicited or unauthorized advertising, solicitations, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other prohibited form of solicitation;</li>
              <li>	any private information of any third party, including addresses, phone numbers, email addresses, number and feature in the personal identity document (e.g., National Insurance numbers, passport numbers) or credit card numbers;</li>
              <li>	any material which does or may infringe any copyright, trademark or other intellectual property or privacy rights of any other person;</li>
              <li>	Distributed any material which is defamatory of any person, obscene, offensive, pornographic, hateful or inflammatory;</li>
              <li>	any material that would constitute, encourage or provide instructions for a criminal offence, dangerous activities or self-harm;</li>
              <li>	any material that is deliberately designed to provoke or antagonize people, especially trolling and bullying, or is intended to harass, harm, hurt, scare, distress, embarrass or upset people;</li>
              <li>	any material that contains a threat of any kind, including threats of physical violence;</li>
              <li>	any material that is racist or discriminatory, including discrimination on the basis of someone’s race, religion, age, gender, disability or sexuality;</li>
              <li>	any answers, responses, comments, opinions, analysis or recommendations that you are not properly licensed or otherwise qualified to provide; or</li>
              <li>	material that, in the sole judgment of Klik, is objectionable or which restricts or inhibits any other person from using the Services, or which may expose Klik, the Services or its users to any harm or liability of any type.</li>
            </ol>
            <br />
            6)	In addition to the above, your access to and use of the Services must, at all times, be compliant with our Community Guidelines, which are updated from time to time. You may not:
            <ol style={{ listStyleType: 'lower-alpha' }}>

              <li>	use or attempt to use another user’s Account without authorization from such user;</li>
              <li>	pose as another person or entity, or use a wallet to engage in a transaction on Klik that is owned or controlled, in whole or in part, by any other person;</li>
              <li>	claim an Klik username for the purpose of reselling it, confusing others, deriving others’ goodwill, or otherwise engage in name squatting;</li>
              <li>	access the Service from a different blockchain address if we’ve blocked any of your other blockchain addresses from accessing the Service, unless you have our written permission first;</li>
              <li>	distribute spam, including through sending unwanted NFTs to other users;</li>
              <li>	use the Service – including through disseminating any software or interacting with any API – that could damage, disable, overburden, or impair the functioning of the Service in any manner;</li>
              <li>	bypass or ignore instructions that control access to the Service, including attempting to circumvent any rate limiting systems, directing traffic through multiple IP addresses, or otherwise obfuscating the source of traffic you send to Klik;</li>
              <li>	use our Service for commercial purposes inconsistent with these Terms or any other instructions;</li>
              <li>	reverse engineer, duplicate, decompile, disassemble, or decode any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any service, area, or code of the Service;</li>
              <li>	sell or resell the Service or attempt to circumvent any Klik fee systems;</li>
              <li>	engage in behaviors that have the intention or the effect of artificially causing an item or collection to appear in a certain area on Metasalt’s site or at the top of search results, or artificially increasing view counts, favorites, or other metrics that Klik might use to surface or sort items, collections, or search results;</li>
              <li>	use the Service or data collected from our Service for any advertising or direct marketing activity (including without limitation, email marketing, SMS marketing, and telemarketing);</li>
              <li>	use the Service, directly or indirectly, for or in connection with money laundering, terrorist financing, or other illicit financial activity, or in any way in connection with the violation of any law or regulation that applies to you or to Klik;</li>
              <li>	use the Service, directly or indirectly, for, on behalf of, for the benefit of, or in connection with (a) any natural or legal person that is the subject of Sanctions; (b) any natural or legal person located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction; or (c) any legal person owned or controlled, directly or indirectly, by any natural or legal person located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction.</li>
              <li>	use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, offering, selling, or buying securities, commodities, options, or debt instruments;</li>
              <li>	use the Service to create, sell, or buy NFTs or other items that give owners’ rights to participate in an ICO or any securities offering, or that are redeemable for securities, commodities, or other financial instruments;</li>
              <li>	use the Service to engage in price manipulation, fraud, or other deceptive, misleading, or manipulative activity;</li>
              <li>	use the Service to buy, sell, or transfer stolen items, fraudulently obtained items, items taken without authorization, and/or any other illegally obtained items;</li>
              <li>	infringe or violate the intellectual property rights or any other rights of others;</li>
              <li>	create, display, purchase, or sell illegal content, such as content that may involve child sexual exploitation;</li>
              <li>	create or display NFTs or other items that promote suicide or self-harm, incite hate or violence against others, or dox another individual;</li>
              <li>	use the Service for any illegal or unauthorized purpose, including creating or displaying illegal content, such as content that may involve child sexual exploitation, or encouraging or promoting any activity that violates the Terms of Service;</li>
              <li>	use the Service with the proceeds of unlawful activity or with a wallet used to engage in unlawful activity;</li>
              <li>	use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service.</li>
            </ol>
            <br />

            7)	Ownership. As between you and Klik, all content, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music on and “look and feel” of the Services, and all intellectual property rights related thereto (the “Metasalt Content”), are either owned or licensed by Klik, it being understood that you or your licensors will own any User Content (as defined below) you upload or transmit through the Services. The “look and feel” includes text, graphics, images, logos, page headers, button icons, urls, and scripts, proprietary content, information and other materials, and all content and other materials contained therein, including, without limitation, the Klik logo and all designs, text, graphics, pictures, data, software, sound files, other files, and the selection and arrangement thereof are the proprietary property of Klik or our affiliates, licensors, or users, as applicable. You agree not to take any action(s) inconsistent with such ownership interests. Use of the Klik Content or materials on the Services for any purpose not expressly permitted by these Terms is strictly prohibited. Such content may not be downloaded, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed or otherwise exploited for any purpose whatsoever without our or, where applicable, our licensors’ prior written consent. We and our licensors reserve all rights not expressly granted in and to their content. We and our affiliates, licensors, and users, as applicable, reserve all rights in connection with the Service and its content, including, without limitation, the exclusive right to create derivative works.
            <ol style={{ listStyleType: 'lower-alpha' }}>

              <li>	Metasalt’s name, logo, trademarks, and any Klik product or service names, designs, logos, and slogans are the intellectual property of Klik or our affiliates or licensors and may not be copied, imitated or used, in whole or in part, without our prior written permission in each instance. You may not use any metatags or other “hidden text” utilizing “Metasalt” or any other name, trademark or product or service name of Klik or our affiliates or licensors without our prior written permission. In addition, the “look and feel” of the Service constitutes the service mark, trademark or trade dress of Klik and may not be copied, imitated or used, in whole or in part, without our prior written permission.</li>
              <li>	All other third-party trademarks, registered trademarks, and product names mentioned on the Service or contained in the content linked to or associated with any NFTs displayed on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable intellectual property rights holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship, or recommendation by Klik.</li>
              <li>	We welcome feedback, comments, and suggestions for improvements to the Service (“Feedback”). You acknowledge and expressly agree that any contribution of Feedback does not and will not give or grant you any right, title, or interest in the Service or in any such Feedback. You agree that Klik may use and disclose Feedback in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim. You hereby assign to Klik any and all right, title, and interest (including, but not limited to, any patent, copyright, trade secret, trademark, show-how, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback.</li>
              <li>	Klik does not have ownership, custody, or control of NFTs or the smart contracts deployed by third parties. Creators of these NFTs or smart contracts are solely responsible for their operation and functionality.</li>
            </ol>
            <br /><br />
            8)	You acknowledge and agree that we may generate revenues, increase goodwill or otherwise increase our value from your use of the Services, including, by way of example and not limitation, sale and marketing of NFTs, through the sale of advertising, sponsorships, promotions, usage data, and except as specifically permitted by us in these Terms or in another agreement you enter into with us, you will have no right to share in any such revenue, goodwill or value whatsoever. You further acknowledge that, except as specifically permitted by us in these Terms or in another agreement you enter into with us, you (i) have no right to receive any income or other consideration from any User Content (defined below) or your use of any musical works, sound recordings or audiovisual clips made available to you on or through the Services, including in any User Content created by you, and (ii) are prohibited from exercising any rights to monetize or obtain consideration from any User Content within the Services or on any third party service ( e.g. , you cannot claim User Content that has been uploaded to a social media platform such as YouTube for monetization).
            <br /><br />
            9)	Subject to the terms and conditions of the Terms, you are hereby granted a non-exclusive, limited, non-transferable, non-sublicensable, revocable, worldwide license to access and use the Services, including to download the Platform on a permitted device, and to access the Klik Content solely for your personal, non-commercial use through your use of the Services and solely in compliance with these Terms. Klik reserves all rights not expressly granted herein in the Services and the Klik Content. You acknowledge and agree that Klik may terminate this license at any time for any reason or no reason.
            <br /><br />
            10)	NO RIGHTS ARE LICENSED WITH RESPECT TO SOUND RECORDINGS AND THE MUSICAL WORKS EMBODIED THEREIN THAT ARE MADE AVAILABLE FROM OR THROUGH THE SERVICE.
            <br /><br />
            11)	You acknowledge and agree that when you view content provided by others on the Services, you are doing so at your own risk. The content on our Services is provided for general information only. It is not intended to amount to advice on which you should rely. You must obtain professional or specialist advice before taking, or refraining from, any action on the basis of the content on our Services.
            <br /><br />
            12)	We make no representations, warranties or guarantees, whether express or implied, that any Klik Content (including User Content) is accurate, complete or up to date. Where our Services contain links to other sites and resources provided by third parties, these links are provided for your information only. We have no control over the contents of those sites or resources. Such links should not be interpreted as approval by us of those linked websites or information you may obtain from them. You acknowledge that we have no obligation to pre-screen, monitor, review, or edit any content posted by you and other users on the Services (including User Content).

            <br /><br />
            13)	User-Generated Content. Users of the Services may be permitted to upload, post or transmit (such as via a stream) or otherwise make available content through the Services including, without limitation, any text, photographs, user videos, sound recordings and the musical works embodied therein, including videos that incorporate locally stored sound recordings from your personal music library and ambient noise (“User Content”). Users of the Services may also extract all or any portion of User Content created by another user to produce additional User Content, including collaborative User Content with other users, that combine and intersperse User Content generated by more than one user. Users of the Services may also overlay music, graphics, stickers, Virtual Items (as defined and further explained Virtual Items Policy) and other elements provided by Klik (“Metasalt Elements”) onto this User Content and transmit this User Content through the Services. The information and materials in the User Content, including User Content that includes Klik Elements, have not been verified or approved by us. The views expressed by other users on the Services (including through use of the virtual gifts) do not represent our views or values.
            <br /><br />
            14)	Whenever you access or use a feature that allows you to upload or transmit User Content through the Services (including via certain third-party social media platforms such as TikTok, Instagram, Facebook, YouTube, Twitter), or to make contact with other users of the Services, you must comply with the standards set out at “Your Access to and Use of Our Services” above. You may also choose to upload or transmit your User Content, including User Content that includes Klik features, on sites or platforms hosted by third parties. If you decide to do this, you must comply with their content guidelines as well as with the standards set out at “Your Access to and Use of Our Services” above. As noted above, these features may not be available to all users of the Services, and we have no liability to you for limiting your right to certain features of the Services.
            <br /><br />
            15)	You warrant that any such contribution does comply with those standards, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of warranty.
            <br /><br />
            16)	Any User Content will be considered non-confidential and non-proprietary. You must not post any User Content on or through the Services or transmit to us any User Content that you consider to be confidential or proprietary. When you submit User Content through the Services, you agree and represent that you own that User Content, or you have received all necessary permissions, clearances from, or are authorized by, the owner of any part of the content to submit it to the Services, to transmit it from the Services to other third-party platforms, and/or adopt any third-party content.
            <br /><br />
            17)	If you only own the rights in and to a sound recording, but not to the underlying musical works embodied in such sound recordings, then you must not post such sound recordings to the Services unless you have all permissions, clearances from, or are authorized by, the owner of any part of the content to submit it to the Services.
            <br /><br />
            18)	You or the owner of your User Content still own the copyright in User Content sent to us, but by submitting User Content via the Services, you hereby grant us an unconditional irrevocable, non-exclusive, royalty-free, fully transferable, perpetual worldwide license to use, modify, adapt, reproduce, make derivative works of, publish and/or transmit, and/or distribute and to authorize other users of the Services and other third-parties to view, access, use, download, modify, adapt, reproduce, make derivative works of, publish and/or transmit your User Content in any format and on any platform, either now known or hereinafter invented.
            <br /><br />
            19)	You further grant us a royalty-free license to use your user name, image, voice, and likeness to identify you as the source of any of your User Content; provided, however, that your ability to provide an image, voice, and likeness may be subject to limitations due to age restrictions.
            <br /><br />
            20)	For the avoidance of doubt, the rights granted in the preceding paragraphs of this Section include, but are not limited to, the right to reproduce sound recordings (and make mechanical reproductions of the musical works embodied in such sound recordings), and publicly perform and communicate to the public sound recordings (and the musical works embodied therein), all on a royalty-free basis. This means that you are granting us the right to use your User Content without the obligation to pay royalties to any third party, including, but not limited to, a sound recording copyright owner, a musical work copyright owner, a performing rights organization, a sound recording professional, any unions or guilds, and engineers, producers or other royalty participants involved in the creation of User Content.
            <br /><br />
            21)	Specific Rules for Musical Works and for Recording Artists. If you are a composer or author of a musical work and are affiliated with a professional, then you must make the proper notification for the royalty-free license you grant through these Terms in your User Content to us. You are solely responsible for ensuring your compliance with your reporting obligations. If you have assigned your rights to a music publisher, then you must obtain the consent of such music publisher to grant the royalty-free license(s) set forth in these Terms in your User Content or have such music publisher enter into these Terms with us. Just because you authored a musical work (e.g., wrote a song) does not mean you have the right to grant us the licenses in these Terms. If you are a recording artist under contract with a record label, then you are solely responsible for ensuring that your use of the Services is in compliance with any contractual obligations you may have to your record label, including if you create any new recordings through the Services that may be claimed by your label.
            <br /><br />
            22)	Through-To-The-Audience Rights. All of the rights you grant in your User Content in these Terms are provided on a through-to-the-audience basis, meaning the owners or operators of third-party services will not have any separate liability to you or any other third party for User Content posted or used on such third-party service via the Services.
            <br /><br />
            23)	Waiver of Rights to User Content. By posting User Content to or through the Services, you waive any rights to prior inspection or approval of any marketing or promotional materials related to such User Content. You also waive any and all rights of privacy, publicity, or any other rights of a similar nature in connection with your User Content, or any portion thereof. To the extent any moral rights are not transferable or assignable, you hereby waive and agree never to assert any and all moral rights, or to support, maintain or permit any action based on any moral rights that you may have in or with respect to any User Content you Post to or through the Services.
            <br /><br />
            24)	We also have the right to disclose your identity to any third party who is claiming that any User Content posted or uploaded by you to our Services constitutes a violation of their intellectual property rights, or of their right to privacy.
            <br /><br />
            25)	We, or authorized third parties, reserve the right to cut, crop, edit or refuse to publish, your content at our or their sole discretion. We have the right to remove, disallow, block or delete any posting you make on our Services if, in our opinion, your post does not comply with the content standards set out at “Your Access to and Use of Our Services” above. In addition, we have the right – but not the obligation – in our sole discretion to remove, disallow, block or delete any User Content (i) that we consider to violate these Terms, or (ii) in response to complaints from other users or third parties, with or without notice and without any liability to you. As a result, we recommend that you save copies of any User Content that you post to the Services on your personal device(s) in the event that you want to ensure that you have permanent access to copies of such User Content. We do not guarantee the accuracy, integrity, appropriateness or quality of any User Content, and under no circumstances will we be liable in any way for any User Content.
            <br /><br />
            26)	You control whether your User Content is made publicly available on the Services to all other users of the Services or only available to people you approve. To restrict access to your User Content, you should select the privacy setting available within the Platform.
            <br /><br />
            27)	We accept no liability in respect of any content submitted by users and published by us or by authorized third parties.
            <br /><br />
            28)	If you wish to file a complaint about information or materials uploaded by other users, contact us.
            <br /><br />
            29)	Klik takes reasonable measures to expeditiously remove from our Services any infringing material that we become aware of. It is Metasalt’s policy, in appropriate circumstances and at its discretion, to disable or terminate the accounts of users of the Services who repeatedly infringe copyrights or intellectual property rights of others.
            <br /><br />
            30)	Our staff is working to develop and evaluate our own product ideas and features. We pay close attention to the interests, feedback, comments, and suggestions we receive from the user community. If you choose to contribute by sending us or our employees any ideas for products, services, features, modifications, enhancements, content, refinements, technologies, content offerings (such as audio, visual, games, or other types of content), promotions, strategies, or product/feature names, or any related documentation, artwork, computer code, diagrams, or other materials (collectively “Feedback”), then regardless of what your accompanying communication may say, the following terms will apply, so that future misunderstandings can be avoided. Accordingly, by sending Feedback to us, you agree that:
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	Klik has no obligation to review, consider, or implement your Feedback, or to return to you all or part of any Feedback for any reason;</li>
              <li>	Feedback is provided on a non-confidential basis, and we are not under any obligation to keep any Feedback you send confidential or to refrain from using or disclosing it in any way; and</li>
              <li>	You irrevocably grant us perpetual and unlimited permission to reproduce, distribute, create derivative works of, modify, publicly perform (including on a through-to-the-audience basis), communicate to the public, make available, publicly display, and otherwise use and exploit the Feedback and derivatives thereof for any purpose and without restriction, free of charge and without attribution of any kind, including by making, using, selling, offering for sale, importing, and promoting commercial products and services that incorporate or embody Feedback, whether in whole or in part, and whether as provided or as modified.</li>
            </ol>
            <br />
            31)	Klik will take down works in response to Digital Millennium Copyright Act (“DMCA”) takedown notices and/or other intellectual property infringement claims and will terminate a user's access to the Service if the user is determined to be a repeat infringer. If you believe that your content has been copied in a way that constitutes copyright or trademark infringement, or violates your publicity or other intellectual property rights, please let us know.
            <br /><br />
            32)	For us to process your infringement claim regarding content on the Service, you must be the rightsholder or someone authorized to act on behalf of the rightsholder. We encourage you to use our form to help ensure the requisite information is included in your notice. If you choose to write to us by email or physical mail instead, your notice must include:
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	Identification of the copyrighted work(s), trademark, publicity rights, or other intellectual property rights that you claim is being infringed;</li>
              <li>	Identification of the allegedly infringing material that is requested to be removed, including a description of the specific location (i.e., urls) on the Service of the material claimed to be infringing, so that we may locate the material;</li>
              <li>	Your contact information – at a minimum, your full legal name (not pseudonym) and email address;</li>
              <li>	A declaration that contains all of the following:</li>
              <li>	A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the intellectual property rights owner, its agent, or the law;</li>
              <li>	A statement that the information in the notice is accurate; and</li>
              <li>	A statement under penalty of perjury that you are authorized to act on behalf of the intellectual property owner of the intellectual property that is allegedly being infringed.</li>
              <li>	Your physical or electronic signature (of your full legal name).</li>
              <li>	Please note that we will forward your notice of intellectual property infringement, including your contact information, to the party who will have their content removed so they understand why it is no longer available on Klik and can also contact you to resolve any dispute.</li>
            </ol>
            <br />
            33)	License to Access and Use Our Service and Content. You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable, and personal license to access and use the Service provided, however, that such license is subject to your compliance with these Terms. If any software, content, or other materials owned by, controlled by, or licensed to us are distributed or made available to you as part of your use of the Service, we hereby grant you a non-commercial, personal, non-assignable, non-sublicensable, non-transferrable, and non-exclusive right and license to access and display such software, content, and materials provided to you as part of the Service (and right to download a single copy of the App onto your applicable equipment or device), in each case for the sole purpose of enabling you to use the Service as permitted by these Terms, provided that your license in any content linked to or associated with any NFTs is solely as set forth by the applicable seller or creator of such NFT.
            <br /><br />
            34)	Apple’s App Store Terms. You are responsible for providing the mobile device, wireless service plan, software, Internet connections, and/or other equipment or services that you need to download, install, and use the App. We do not guarantee that the App can be accessed and used on any particular device or with any particular service plan. We do not guarantee that the App or Service will be available in any particular geographic location. The following terms and conditions apply to you only if you are using the App from the Apple App Store: To the extent the other terms and conditions of these Terms are less restrictive than, or otherwise conflict with, the terms and conditions of this paragraph, the more restrictive or conflicting terms and conditions in this paragraph apply, but solely with respect to your use of the App from the Apple App Store. You acknowledge and agree that these Terms are solely between you and Klik, not Apple, and that Apple has no responsibility for the App or content thereof. Your use of the App must comply with the App Store’s applicable terms of use. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App. In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price, if any, for the App to you. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be solely governed by these Terms. You acknowledge that Apple is not responsible for addressing any claims of yours or any third party relating to the App or your possession and/or use of the App, including, but not limited to: (a) product liability claims, (b) any claim that the App fails to conform to any applicable legal or regulatory requirement, and (c) claims arising under consumer protection or similar legislation. You acknowledge that, in the event of any third-party claim that the App or your possession and use of that App infringes that third party’s intellectual property rights, Klik, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms. You must comply with applicable third-party terms of agreement when using the App. You acknowledge and agree that Apple, and Apple’s subsidiaries, are third-party beneficiaries of these Terms as they relate to your use of the App, and that, upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary thereof.
            <br /><br />
            35)	Windows Phone Store. By downloading the Platform from the Windows Phone Store (or its successors) operated by Microsoft, Inc. or its affiliates, you specifically acknowledge and agree that: You may install and use one copy of the Platform on up to five (5) Windows Phone enabled devices that are affiliated with the Microsoft account you use to access the Windows Phone Store. Beyond that, we reserve the right to apply additional conditions or charge additional fees. You acknowledge that Microsoft Corporation, your phone manufacturer and network operator have no obligation whatsoever to furnish any maintenance and support services with respect to the Platform.
            <br /><br />
            36)	Amazon Appstore. By downloading the Platform from the Amazon Appstore (or its successors) operated by Amazon Digital Services, Inc. or affiliates (“Amazon”), you specifically acknowledge and agree that: to the extent of any conflict between (a) the Amazon Appstore Terms of Use or such other terms which Amazon designates as default end user license terms for the Amazon Appstore (“Amazon Appstore EULA Terms”), and (b) the other terms and conditions in these Terms, the Amazon Appstore EULA Terms shall apply with respect to your use of the Platform that you download from the Amazon Appstore, and Amazon does not have any responsibility or liability related to compliance or non-compliance by Klik or you (or any other user) under these Terms or the Amazon Appstore EULA Terms.
            <br /><br />
            37)	Google Play. By downloading the Platform from Google Play (or its successors) operated by Google, Inc. or one of its affiliates (“Google”), you specifically acknowledge and agree that: to the extent of any conflict between (a) the Google Play Terms of Services and the Google Play Business and Program Policies or such other terms which Google designates as default end user license terms for Google Play (all of which together are referred to as the “Google Play Terms”), and (b) the other terms and conditions in these Terms, the Google Play Terms shall apply with respect to your use of the Platform that you download from Google Play, and you hereby acknowledge that Google does not have any responsibility or liability related to compliance or non-compliance by Klik or you (or any other user) under these Terms or the Google Play Terms.
            <br /><br />
            38)	Indemnification. By agreeing to these Terms and accessing the Service, you agree, to the fullest extent permitted by applicable law, to indemnify, defend, and hold harmless Klik, and our respective past, present, and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors, and assigns (individually and collectively, the “Metasalt Parties”), from and against all actual or alleged claims, damages, awards, judgments, losses, liabilities, obligations, taxes, penalties, interest, fees, expenses (including, without limitation, attorneys’ fees and expenses), and costs (including, without limitation, court costs, costs of settlement, and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract, or otherwise (collectively, “Claims”), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to (a) your use or misuse of the Service, content, NFTs, or content linked to or associated with any NFTs (b) any Feedback you provide, (c) your violation or breach of any term of these Terms or applicable law, and (d) your violation of the rights of or obligations to a third party, including another user or third party, and (e) your negligence or willful misconduct. You agree to promptly notify Klik of any Claims and cooperate with the Klik Parties in defending such Claims. You further agree that the Klik Parties shall have control of the defense or settlement of any Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND KLIK.
            <br /><br />
            39)	Disclaimers
            <ol style={{ listStyleType: 'lower-roman' }}>
              <li>	YOUR ACCESS TO AND USE OF THE SERVICE IS AT YOUR OWN RISK. YOU UNDERSTAND AND AGREE THAT THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND KLIK EXPRESSLY DISCLAIMS WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. KLIK (AND ITS SUPPLIERS) MAKE NO WARRANTY OR REPRESENTATION AND DISCLAIM ALL RESPONSIBILITY FOR WHETHER THE SERVICE: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE. KLIK DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. KLIK WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE SERVICE. WHILE KLIK ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE SAFE, KLIK CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, CONTENT LINKED TO OR ASSOCIATED WITH ANY NFTS, OR ANY NFTS YOU INTERACT WITH USING OUR SERVICE OR OUR SERVICE PROVIDERS’ SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. NO ADVICE OR INFORMATION, WHETHER ORAL OR OBTAINED FROM THE KLIK PARTIES OR THROUGH THE SERVICE, WILL CREATE ANY WARRANTY OR REPRESENTATION NOT EXPRESSLY MADE HEREIN. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD KLIK RESPONSIBLE FOR ANY BREACH OF SECURITY.</li>
              <li>	WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF OR LOSS OF USE OF NFTS, CONTENT, AND/OR CONTENT LINKED TO OR ASSOCIATED WITH NFTS, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES, OR CLAIMS ARISING FROM: (A) USER ERROR, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (B) SERVER FAILURE OR DATA LOSS; (C) UNAUTHORIZED ACCESS OR USE; (D) ANY UNAUTHORIZED THIRD-PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR NFTS.</li>
              <li>	NFTS EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE ASSOCIATED BLOCKCHAIN (E.G., ETHEREUM NETWORK). ANY TRANSFERS OR SALES OCCUR ON THE ASSOCIATED BLOCKCHAIN (E.G., ETHEREUM). KLIK AND/OR ANY OTHER KLIK PARTY CANNOT AFFECT OR OTHERWISE CONTROL THE TRANSFER OF TITLE OR RIGHT IN ANY NFTS OR UNDERLYING OR ASSOCIATED CONTENT OR ITEMS.</li>
              <li>	NO KLIK PARTY IS RESPONSIBLE OR LIABLE FOR ANY SUSTAINED LOSSES OR INJURY DUE TO VULNERABILITY OR ANY KIND OF FAILURE, ABNORMAL BEHAVIOR OF SOFTWARE (E.G., WALLET, SMART CONTRACT), BLOCKCHAINS OR ANY OTHER FEATURES OF THE NFTS. NO KLIK PARTY IS RESPONSIBLE FOR LOSSES OR INJURY DUE TO LATE REPORTS BY DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY ISSUES WITH THE BLOCKCHAIN SUPPORTING THE NFTS, INCLUDING FORKS, TECHNICAL NODE ISSUES OR ANY OTHER ISSUES HAVING LOSSES OR INJURY AS A RESULT.</li>
              <li>	Some jurisdictions do not allow the exclusion of implied warranties in contracts with consumers, so the above exclusion may not apply to you.</li>
            </ol>
            <br />
            40)	Limitation of Liability
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	TO THE FULLEST EXTENT PERMITTED BY LAW, YOU AGREE THAT IN NO EVENT WILL KLIK OR ITS SERVICE PROVIDERS BE LIABLE TO YOU OR ANY THIRD PARTY (A) FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES ARISING FROM THESE TERMS OR THE SERVICE, PRODUCTS OR THIRD-PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY STRICT LIABILITY OR TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF KLIK OR ITS SERVICE PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (B) FOR ANY OTHER CLAIM, DEMAND, OR DAMAGES WHATSOEVER RESULTING FROM OR ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF THE DELIVERY, USE, OR PERFORMANCE OF THE SERVICE. ACCESS TO, AND USE OF, THE SERVICE, PRODUCTS OR THIRD-PARTY SITES, AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.</li>
              <li>	ANY LOSS OR DAMAGE WHICH MAY BE INCURRED BY YOU AS A RESULT OF: ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY ADVERTISER OR SPONSOR WHOSE ADVERTISING APPEARS ON THE SERVICE; ANY CHANGES WHICH WE MAY MAKE TO THE SERVICES, OR FOR ANY PERMANENT OR TEMPORARY CESSATION IN THE PROVISION OF THE SERVICES (OR ANY FEATURES WITHIN THE SERVICES); THE DELETION OF, CORRUPTION OF, OR FAILURE TO STORE, ANY CONTENT AND OTHER COMMUNICATIONS DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE SERVICES; YOUR FAILURE TO PROVIDE US WITH ACCURATE ACCOUNT INFORMATION; OR YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL.</li>
              <li>	PLEASE NOTE THAT WE ONLY PROVIDE OUR PLATFORM FOR DOMESTIC AND PRIVATE USE. YOU AGREE NOT TO USE OUR PLATFORM FOR ANY COMMERCIAL OR BUSINESS PURPOSES, AND WE HAVE NO LIABILITY TO YOU FOR ANY LOSS OF PROFIT, LOSS OF BUSINESS, LOSS OF GOODWILL OR BUSINESS REPUTATION, BUSINESS INTERRUPTION, OR LOSS OF BUSINESS OPPORTUNITY.</li>
              <li>	IF DEFECTIVE DIGITAL CONTENT THAT WE HAVE SUPPLIED DAMAGES A DEVICE OR DIGITAL CONTENT BELONGING TO YOU AND THIS IS CAUSED BY OUR FAILURE TO USE REASONABLE CARE AND SKILL, WE WILL EITHER REPAIR THE DAMAGE OR PAY YOU COMPENSATION. HOWEVER, WE WILL NOT BE LIABLE FOR DAMAGE THAT YOU COULD HAVE AVOIDED BY FOLLOWING OUR ADVICE TO APPLY AN UPDATE OFFERED TO YOU FREE OF CHARGE OR FOR DAMAGE THAT WAS CAUSED BY YOU FAILING TO CORRECTLY FOLLOW INSTALLATION INSTRUCTIONS OR TO HAVE IN PLACE THE MINIMUM SYSTEM REQUIREMENTS ADVISED BY US.</li>
              <li>	THESE LIMITATIONS ON OUR LIABILITY TO YOU SHALL APPLY WHETHER OR NOT WE HAVE BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.</li>
              <li>	YOU ARE RESPONSIBLE FOR ANY MOBILE CHARGES THAT MAY APPLY TO YOUR USE OF OUR SERVICE, INCLUDING TEXT-MESSAGING AND DATA CHARGES. IF YOU’RE UNSURE WHAT THOSE CHARGES MAY BE, YOU SHOULD ASK YOUR SERVICE PROVIDER BEFORE USING THE SERVICE.</li>
              <li>	TO THE FULLEST EXTENT PERMITTED BY LAW, ANY DISPUTE YOU HAVE WITH ANY THIRD PARTY ARISING OUT OF YOUR USE OF THE SERVICES, INCLUDING, BY WAY OF EXAMPLE AND NOT LIMITATION, ANY CARRIER, COPYRIGHT OWNER OR OTHER USER, IS DIRECTLY BETWEEN YOU AND SUCH THIRD PARTY, AND YOU IRREVOCABLY RELEASE US AND OUR AFFILIATES FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES.</li>
              <li>	NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF KLIK ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, NFTS, OR ANY KLIK PRODUCTS OR SERVICES EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT RECEIVED BY KLIK FOR ITS SERVICE TO YOU DIRECTLY RELATING TO THE ITEMS THAT ARE THE SUBJECT OF THE CLAIM. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</li>
              <li>	Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.</li>
            </ol>
            <br />
            41)	Privacy Policy. Please refer to our Privacy Policy for information about how we collect, use, and share information from and/or about you ("Your Information"). By submitting Your Information through our Service, you agree to the terms of our Privacy Policy and you expressly consent to the collection, use, and disclosure of Your Information in accordance with the Privacy Policy.
            <br /><br />
            42)	Modifications to the Service. We reserve the right in our sole discretion to modify, suspend, or discontinue, temporarily or permanently, the Service (or any features or parts thereof) at any time and without liability as a result.
            <br /><br />
            43)	Dispute Resolution; Arbitration
            <ol style={{ listStyleType: 'lower-alpha' }}>
              <li>	Dispute Resolution. Please read the following arbitration agreement in this Section (“Arbitration Agreement”) carefully. It requires you to arbitrate disputes with Klik and limits the manner in which you can seek relief from us. This section does not govern disputes between users or between users and third parties. Klik does not provide dispute resolution services for such disagreements and the parties must resolve those disputes directly.</li>
              <li>	Applicability of Arbitration Agreement. You agree that any dispute, controversy, or claim relating in any way to your access or use of the Service, to any products sold or distributed through the Service, or to any aspect of your relationship with Klik, will be resolved by binding arbitration, rather than in court, including threshold questions of the arbitrability of such dispute, controversy, or claim except that (1) you or Klik may assert claims in small claims court, but only if the claims qualify, the claims remain only in such court, and the claims remain on an individual, non-representative, and non-class basis; and (2) you or Klik may seek injunctive or equitable relief in a court of proper jurisdiction if the claim relates to intellectual property infringement or other misuse of intellectual property rights.</li>
              <li>	Dispute resolution process. You and Klik both agree to engage in good-faith efforts to resolve disputes prior to either party initiating an arbitration, small claims court proceeding, or equitable relief for intellectual property infringement. You must initiate this dispute resolution process by sending a letter describing the nature of your claim and desired resolution to: Klik, Attn: Legal Department, 160 Varick Street, Third Floor, New York, NY 10013. Both parties agree to meet and confer personally, by telephone, or by videoconference (hereinafter “Conference”) to discuss the dispute and attempt in good faith to reach a mutually beneficial outcome that avoids the expenses of arbitration or, where applicable, litigation. If you are represented by counsel, your counsel may participate in the Conference as well, but you agree to fully participate in the Conference. Likewise, if Klik is represented by counsel, its counsel may participate in the Conference as well, but Klik agrees to have a company representative fully participate in the Conference. The statute of limitations and any filing fee deadlines shall be tolled while the parties engage in the informal dispute resolution process and Conference required by this paragraph. If the parties do not reach agreement to resolve the dispute within thirty (30) days after initiation of this dispute resolution process, either party may commence arbitration, file an action in small claims court, or file a claim for injunctive or equitable relief in a court of proper jurisdiction for matters relating to intellectual property infringement, if the claims qualify.</li>
              <li>	Arbitration Rules and Forum. The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement. To begin an arbitration proceeding after participating in the dispute resolution process, you must send a letter requesting arbitration and describing your claim to our registered agent at Klik, Attn: Legal Department, 160 Varick Street, Third Floor, New York, NY 10013. The arbitration will be conducted by JAMS, an established alternative dispute resolution provider. Disputes involving claims and counterclaims under $250,000, not inclusive of attorneys’ fees, interest, claimed punitive or other damages, or any claim in excess of the bona fide verifiable value of actual lost property shall be subject to JAMS’s most current version of the Streamlined Arbitration Rules and the JAMS Consumer Minimum Standards then in effect; all other claims shall be subject to JAMS’s most current version of the Comprehensive Arbitration Rules and Procedures and the JAMS Consumer Minimum Standards then in effect. JAMS’s rules are available at jamsadr.com or by calling JAMS at 800-352- 5267. If JAMS is not available to arbitrate, the parties will select an alternative arbitral forum. If the arbitrator finds that you cannot afford to pay JAMS filing, administrative, hearing, and/or other fees and cannot obtain a waiver from JAMS, Klik will pay them for you if you complied with the dispute resolution process set forth above. In addition, Klik will reimburse all such JAMS filing, administrative, hearing, and/or other fees for claims totaling less than $10,000 unless
                (a) a resolution of your claim results in a smaller monetary judgment than Klik may have offered you to settle the claim, at any point, or (b) the arbitrator determines the claims are frivolous or you did not comply with the dispute resolution process set forth above, except that if you have initiated the arbitration claim, you will still be required to pay the lesser of $250 or the maximum amount permitted under the JAMS Rules for arbitration claims initiated by you. You are still responsible for all additional costs that you incur in the arbitration, including without limitation, fees for attorneys or expert witnesses. You may choose to have the arbitration conducted by telephone or videoconference, based on written submissions, in person in your hometown area (if you live in the United States), or at another mutually agreed upon location that is reasonably convenient to you. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.</li>
              <li>	Authority of Arbitrator. The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability, or formation of this Arbitration Agreement including, but not limited to, any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of you and Klik. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and these Terms. The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.</li>
              <li>	Waiver of Jury Trial. YOU AND KLIK HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. You and Klik are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in the second bullet of this Section 16, above (“Applicability of Arbitration Agreement”). An arbitrator can award on an individual basis the same damages and relief as a court and must follow these Terms as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.</li>
              <li>	Waiver of Class Actions and Class Arbitrations. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A REPRESENTATIVE (INCLUDING, WITHOUT LIMITATION, PAGA) OR COLLECTIVE CLASS BASIS. ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE USER, PERSON, OR ENTITY CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER USER, PERSON, OR ENTITY. Accordingly, under the arbitration procedures outlined in this section, an arbitrator shall not combine or consolidate more than one party’s claims without the written consent of all affected parties to an arbitration proceeding. Without limiting the generality of the foregoing, you and Klik agree that no dispute shall proceed by way of class arbitration without the written consent of all affected parties. If a decision is issued stating that applicable law precludes enforcement of any part of this subsection’s limitations as to a given claim for relief, then that claim must be severed from the arbitration and brought in the state or federal courts located in New York County in the State of New York. All other claims shall be arbitrated.</li>
              <li>	Severability. Except as provided in this Section, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Arbitration Agreement shall continue in full force and effect.</li>
              <li>	Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with Klik.</li>
              <li>	Modification. Notwithstanding any provision in these Terms to the contrary, we agree that if Klik makes any future material change to this Arbitration Agreement, you may reject that change within thirty (30) days of such change becoming effective by writing to Klik at the following address: Klik, Attn: Legal Department, 160 Varick Street, Third Floor, New York, NY 10013.</li>
            </ol>
            <br />
            44)	Governing Law and Venue. These Terms and your access to and use of the Service shall be governed by and construed and enforced in accordance with the laws of the State of New York (without regard to conflict of law rules or principles of the State of New York, or any other jurisdiction that would cause the application of the laws of any other jurisdiction). Any dispute between the parties that is not subject to arbitration as set forth in Section 16 or cannot be heard in small claims court, shall be resolved in the state or federal courts of New York County in the State of New York, and the United States, respectively, sitting in the State of New York.
            <br /><br />
            45)	Termination. If you breach any of the provisions of these Terms, all licenses granted by Klik will terminate automatically. Additionally, notwithstanding anything contained in these Terms, we reserve the right, with or without notice and in our sole discretion, to suspend, restrict, disable, terminate, or delete your Account and/or your ability to access or use the Service (or any part of the foregoing) at any time and for any or no reason, and you acknowledge and agree that we shall have no liability or obligation to you in such event and that you will not be entitled to a refund of any amounts that you have already paid to us. If we terminate your Account or restrict your access or use of the Service, you retain ownership of your NFTs. You may still access your NFTs through public blockchains and other web3 wallets, platforms, and/or websites.
            <br /><br />
            46)	Severability. If any term, clause, or provision of these Terms is held invalid or unenforceable, then that term, clause, or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause, or provision, or any other term, clause, or provision of these Terms.
            <br /><br />
            47)	Injunctive Relief. You agree that a breach of these Terms will cause irreparable injury to Klik for which monetary damages would not be an adequate remedy and Klik shall be entitled to equitable relief in addition to any remedies it may have hereunder or at law without a bond, other security, or proof of damages.
            <br /><br />
            48)	California Residents. If you are a California resident, in accordance with Cal. Civ. Code § 1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 1625 North Market Blvd., Suite N 112 Sacramento, CA 95834, or by telephone at (800) 952-5210.
            <br /><br />
            49)	Export Laws. You agree that you will not export or re-export, directly or indirectly, the Service, and/or other information or materials provided by Klik hereunder, to any country for which the United States or any other relevant jurisdiction requires any export license or other governmental approval at the time of export without first obtaining such license or approval. In particular, but without limitation, the Service may not be exported or re-exported (a) into any U.S. embargoed countries or any country that has been designated by the U.S. Government as a “terrorist supporting” country, or (b) to anyone listed on any U.S. Government list of prohibited or restricted parties, including the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce Denied Person’s List or Entity List. By using the Service, you represent and warrant that you are not located in any such country or on any such list. You are responsible for and hereby agree to comply at your sole expense with all applicable United States export laws and regulations.
            <br /><br />
            50)	Survival. All sections which by their nature should survive the termination of these Terms shall continue in full force and effect subsequent to and notwithstanding any termination of these Terms by Klik or you. Termination will not limit any of Metasalt’s other rights or remedies at law or in equity.
            <br /><br />
            51)	Miscellaneous. These Terms (and any other applicable terms or policies incorporated by reference in these Terms) constitute the entire agreement between you and Klik relating to your access to and use of the Service. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of Klik, and Metasalt’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for reference only and shall not be read to have any legal effect. The Service is operated by us in the United States. Those who choose to access the Service from locations outside the United States do so at their own initiative and are responsible for compliance with applicable local laws. You and Klik agree that the United Nations Convention on Contracts for the International Sale of Goods will not apply to the interpretation or construction of these Terms. Except as otherwise provided herein, these Terms are intended solely for the benefit of the parties and are not intended to confer third-party beneficiary rights upon any other person or entity.

          </div>
        </section>
      </LayoutScreen>
    </LayoutPage>
  )
};

export default memo(Privacy);
